<a href="https://colab.research.google.com/github/HTS05/Numpy_practice/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Create a 5×5 matrix with values 1,2,3,…,25
import numpy as np
np.arange(1, 26).reshape(5, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Generate a 4×4 identity matrix using NumPy
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Create a 1D array of numbers from 100 to 200 with step size 10
np.arange(100, 201, 10)

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200])

In [ ]:
# Generate a random 3×3 matrix and find its determinant
a = np.random.rand(3,3)
print(a)
np.linalg.det(a)

[[0.24564394 0.21587466 0.1298096 ]
 [0.21368494 0.50322482 0.92135104]
 [0.04259309 0.43466761 0.20076052]]


np.float64(-0.06507366870551107)

In [ ]:
# Create a NumPy array of 10 random integers between 1 and 100
np.random.randint(1, 101, 10)

array([61, 60, 30, 31,  8, 43, 94, 59, 21,  7])

In [ ]:
# Reshape a 1D array of size 12 into a 3×4 matrix
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Create two 3×3 matrices and perform matrix multiplication
m1 = np.random.randint(1,10,(3,3))
m2 = np.random.randint(1,10,(3,3))
m1 @ m2

array([[ 67, 120, 114],
       [ 32,  40,  28],
       [ 67, 113, 119]])

In [ ]:
# Find eigenvalues and eigenvectors of a given 2×2 matrix
m = np.array([[4, -2],[1,1]])
np.linalg.eig(m)

EigResult(eigenvalues=array([3., 2.]), eigenvectors=array([[0.89442719, 0.70710678],
       [0.4472136 , 0.70710678]]))

In [ ]:
#  Create a 5×5 matrix with random values and extract its diagonal elements
m = np.random.rand(5,5)
np.diag(m)

array([0.31740044, 0.58788544, 0.77732135, 0.82343137, 0.28176898])

In [ ]:
# Generate a 1D array and normalize it (scale values between 0 and 1)
arr = np.array([10,20,30,40,50])
(arr - arr.min())/(arr.max()-arr.min())

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Write a program to sort a NumPy array by row and column
arr = np.random.randint(1, 100, (3, 3))
print("Original:\n", arr)
print("Row-wise sort:\n", np.sort(arr, axis=1))
print("Column-wise sort:\n", np.sort(arr, axis=0))

Original:
 [[44 82 52]
 [73 11 20]
 [28 38 76]]
Row-wise sort:
 [[44 52 82]
 [11 20 73]
 [28 38 76]]
Column-wise sort:
 [[28 11 20]
 [44 38 52]
 [73 82 76]]


In [ ]:
# Find the indices of maximum and minimum values in a NumPy array
arr = np.random.randint(1, 100, 10)
print("Array:", arr)
print("Max index:", arr.argmax())
print("Min index:", arr.argmin())

Array: [61 54 98 70 70 74 83 80 82 75]
Max index: 2
Min index: 1


In [ ]:
# Create a 2D array and flatten it using ravel() and flatten()
m= np.array([[1, 2], [3, 4]])
print("Using ravel:", m.ravel())
print("Using flatten:", m.flatten())

Using ravel: [1 2 3 4]
Using flatten: [1 2 3 4]


In [ ]:
# Create a 3×3 matrix and compute its inverse using NumPy
m= np.random.rand(3, 3)
print("Matrix:\n", m)
print("Inverse:\n", np.linalg.inv(m))

Matrix:
 [[0.42175735 0.46418269 0.13469626]
 [0.589371   0.77411317 0.13272713]
 [0.90056918 0.96319465 0.14088708]]
Inverse:
 [[ 2.23082289 -7.64312418  5.06765041]
 [-4.33527283  7.35111003 -2.78057248]
 [15.37899173 -1.40103529 -6.28543962]]


In [ ]:
# Write a NumPy program to generate a random permutation of numbers 1 to 10
np.random.permutation(np.arange(1, 11))

array([ 5,  2,  1, 10,  8,  4,  6,  9,  3,  7])

In [ ]:
# Create a NumPy array with values from 0 to 20 and replace all even numbers with -1
arr= np.arange(21)
arr[arr % 2 == 0] = -1
arr

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9, -1, 11, -1, 13, -1, 15, -1,
       17, -1, 19, -1])

In [ ]:
# Write a program to compute the dot product of two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

np.int64(32)

In [ ]:
# Generate a 5×5 random matrix and compute its trace
m= np.random.rand(5, 5)
print("Matrix:\n", m)
print("Trace:", np.trace(m))

Matrix:
 [[0.61042254 0.14609345 0.99368682 0.65463388 0.40062635]
 [0.53885753 0.03107034 0.18604698 0.12102588 0.66020264]
 [0.50292422 0.36047861 0.83002838 0.15586944 0.53869068]
 [0.6465685  0.84480026 0.02669695 0.92628411 0.48105944]
 [0.70839615 0.0863291  0.11769503 0.46531272 0.46314327]]
Trace: 2.8609486321597237


In [ ]:
# Write a NumPy program to split a 1D array into 3 equal parts
arr= np.arange(9)
np.split(arr, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [ ]:
#  Create a 3D array of shape (3,3,3) and find its mean across axis=0
m = np.random.rand(3, 3, 3)
m.mean(axis=0)

array([[0.36809425, 0.51812882, 0.58461402],
       [0.4016052 , 0.27760183, 0.49576823],
       [0.54881804, 0.49505999, 0.20253961]])

In [ ]:
#  Write a program to find the cumulative sum of a NumPy array
arr = np.array([1, 2, 3, 4, 5])
np.cumsum(arr)

array([ 1,  3,  6, 10, 15])

In [ ]:
# Create a 4×4 matrix with random integers and extract its upper triangular matrix
m = np.random.randint(1, 10, (4, 4))
print("Matrix:\n", m)
print("Upper Triangular:\n", np.triu(m))

Matrix:
 [[7 8 9 6]
 [8 5 1 3]
 [1 9 1 5]
 [6 8 8 1]]
Upper Triangular:
 [[7 8 9 6]
 [0 5 1 3]
 [0 0 1 5]
 [0 0 0 1]]


In [ ]:
#Write a program to generate a matrix of size 6×6 with checkerboard pattern (0,1)
checker = np.indices((6, 6)).sum(axis=0) % 2
checker

array([[0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0]])

In [ ]:
# Generate a 3×3 random matrix and apply element-wise square root
m = np.random.rand(3, 3)
np.sqrt(m)

array([[0.99413455, 0.36091205, 0.66398827],
       [0.48551258, 0.72764249, 0.89360515],
       [0.83622544, 0.83433259, 0.87284695]])

In [ ]:
# Create a 1D array of 20 elements and reverse it without using Python slicing
arr= np.arange(20)
np.flip(arr)

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [ ]:
# Write a program to merge two NumPy arrays vertically and horizontally
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("Vertical:\n", np.vstack((a, b)))
print("Horizontal:\n", np.hstack((a, b)))

Vertical:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Create a 2D NumPy array and compute row-wise and column-wise sum
m = np.arange(1, 10).reshape(3, 3)
print("Row-wise sum:", m.sum(axis=1))
print("Column-wise sum:", m.sum(axis=0))

Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]


In [ ]:
#  Write a NumPy program to replace NaN values in an array with the mean of that column
m= np.array([[1, np.nan, 3], [4, 5, np.nan]])
col_means = np.nanmean(m, axis=0)
inds = np.where(np.isnan(m))
m[inds] = np.take(col_means, inds[1])
m

array([[1., 5., 3.],
       [4., 5., 3.]])

In [ ]:
# Generate two 1D arrays and compute cosine similarity using NumPy
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
cos_sim = np.dot(x, y) / (np.linalg.norm(x) * np.linalg.norm(y))
cos_sim

np.float64(0.9746318461970762)

In [ ]:
# Create a 4×4 array and rotate it by 90 degrees using NumPy
m = np.arange(16).reshape(4, 4)
np.rot90(m)

array([[ 3,  7, 11, 15],
       [ 2,  6, 10, 14],
       [ 1,  5,  9, 13],
       [ 0,  4,  8, 12]])

In [ ]:
# Write a program to create a structured NumPy array with fields (name, age, marks)
dt = np.dtype([('name', 'U10'), ('age', 'i4'), ('marks', 'f4')])
students = np.array([('Tony', 20, 85.5), ('Steve', 21, 90.0)], dtype=dt)
students

array([('Tony', 20, 85.5), ('Steve', 21, 90. )],
      dtype=[('name', '<U10'), ('age', '<i4'), ('marks', '<f4')])

In [ ]:
# Generate a random 3×3 matrix and compute its rank
m = np.random.rand(3, 3)
np.linalg.matrix_rank(m)

np.int64(3)

In [ ]:
#  Create a 5×5 random matrix and normalize each row to have unit length
m= np.random.rand(5, 5)
row_norm = m / np.linalg.norm(m, axis=1, keepdims=True)
row_norm

array([[0.74399927, 0.37728339, 0.01621207, 0.10861793, 0.54042729],
       [0.39946187, 0.0593893 , 0.39957714, 0.41345747, 0.7115435 ],
       [0.45389349, 0.76956635, 0.42868084, 0.03709183, 0.12886142],
       [0.66194984, 0.170253  , 0.28101064, 0.61834245, 0.26743591],
       [0.40093908, 0.53100094, 0.41492957, 0.3580112 , 0.50689969]])

In [ ]:
# Write a NumPy program to check whether two arrays are equal element-wise
np.array_equal([1, 2, 3], [1, 2, 3])

True

In [ ]:
# Generate a random dataset of 1000 numbers and compute histogram using NumPy
data = np.random.randn(1000)
hist, bins = np.histogram(data, bins=10)
print("Histogram:", hist)
print("Bins:", bins)

Histogram: [ 12  39 111 193 250 186 134  55  16   4]
Bins: [-2.85095486 -2.2399869  -1.62901893 -1.01805096 -0.40708299  0.20388498
  0.81485295  1.42582091  2.03678888  2.64775685  3.25872482]


In [ ]:
# Create a 2D array and apply broadcasting to add a 1D array
m = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([1, 0, 1])
m + v

array([[2, 2, 4],
       [5, 5, 7]])

In [ ]:
# Write a program to find unique values and their counts in a NumPy array
arr= np.array([1, 2, 2, 3, 4, 4, 4])
vals, counts = np.unique(arr, return_counts=True)
print("Values:", vals)
print("Counts:", counts)

Values: [1 2 3 4]
Counts: [1 2 1 3]


In [ ]:
# Create two arrays and find Pearson correlation coefficient using NumPy
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.corrcoef(x, y)[0, 1]

np.float64(1.0)

In [ ]:
# Write a NumPy program to compute numerical gradient of a 1D array
arr = np.array([1, 2, 4, 7, 11])
np.gradient(arr)

array([1. , 1.5, 2.5, 3.5, 4. ])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#Generate a random 3×3 matrix and perform Singular Value Decomposition (SVD)
m40 = np.random.rand(3, 3)
U, S, V = np.linalg.svd(m40)
print("U:\n", U)
print("S:", S)
print("V:\n", V)

U:
 [[-0.41271262  0.81335855 -0.4100197 ]
 [-0.48478186 -0.57723701 -0.65710272]
 [-0.77113866 -0.07242447  0.63253447]]
S: [1.71330284 0.60626894 0.43625089]
V:
 [[-0.50553843 -0.40198239 -0.76344028]
 [ 0.17800647  0.81720725 -0.54816604]
 [ 0.84424202 -0.41301631 -0.3415742 ]]
